# https://github.com/GoogleContainerTools/skaffold/blob/master/examples/jib-gradle/skaffold.yaml#L1-L6 @ 2019 10 08
apiVersion: skaffold/v1beta15
kind: Config
build:
  artifacts:
    - image: gcr.io/ktor-jib/kjib-image
      jib: {}